[supervisord]
environment =
    AA_USER = allianceserver,  ; The user under which the processes will run
    AA_PROJECT_NAME = myauth,  ; The name of the project
    AA_PROJECT_DIRECTORY = /home/mbroekman/development/allianceauth/allianceauth-dev/aa-industry/myauth,  ; The directory of the project
    AA_VENV_DIRECTORY = /home/mbroekman/development/allianceauth/allianceauth-dev/aa-industry/build_venv,  ; The directory of the virtual environment
    AA_COMMAND_CELERY = /home/mbroekman/development/allianceauth/allianceauth-dev/aa-industry/build_venv/bin/celery,  ; The command to run Celery
    AA_COMMAND_GUNICORN = None,  ; The command to run Gunicorn
    AA_COMMAND_MEMMON = None  ; The command to run Memmon

[program:beat]
command = %(ENV_AA_COMMAND_CELERY)s
    -A %(ENV_AA_PROJECT_NAME)s beat
directory = %(ENV_AA_PROJECT_DIRECTORY)s
user = %(ENV_AA_USER)s
stdout_logfile = %(ENV_AA_PROJECT_DIRECTORY)s/log/%(program_name)s.log
stderr_logfile = %(ENV_AA_PROJECT_DIRECTORY)s/log/%(program_name)s.log
autostart = true
autorestart = true
startsecs = 10
priority = 998

[program:worker]
command = %(ENV_AA_COMMAND_CELERY)s
    -A %(ENV_AA_PROJECT_NAME)s worker
    --pool=threads
    --concurrency=5
    -n %(program_name)s_%(process_num)02d
directory = %(ENV_AA_PROJECT_DIRECTORY)s
user = %(ENV_AA_USER)s
numprocs = 1
process_name = %(program_name)s_%(process_num)02d
stdout_logfile = %(ENV_AA_PROJECT_DIRECTORY)s/log/%(program_name)s.log
stderr_logfile = %(ENV_AA_PROJECT_DIRECTORY)s/log/%(program_name)s.log
autostart = true
autorestart = true
startsecs = 10
stopwaitsecs = 600
killasgroup = true
priority = 998

[program:worker_services]
command = %(ENV_AA_COMMAND_CELERY)s
    -A %(ENV_AA_PROJECT_NAME)s worker
    --pool=threads
    --concurrency=1
    -n %(program_name)s_%(process_num)02d
    -Q services
directory = %(ENV_AA_PROJECT_DIRECTORY)s
user = %(ENV_AA_USER)s
numprocs = 1
process_name = %(program_name)s_%(process_num)02d
stdout_logfile = %(ENV_AA_PROJECT_DIRECTORY)s/log/%(program_name)s.log
stderr_logfile = %(ENV_AA_PROJECT_DIRECTORY)s/log/%(program_name)s.log
autostart = true
autorestart = true
startsecs = 10
stopwaitsecs = 600
killasgroup = true
priority = 998



[eventlistener:memmon]
command = %(ENV_AA_COMMAND_MEMMON)s
    -p worker=256MB
    -p worker_services=256MB
    -p gunicorn=256MB
directory = %(ENV_AA_PROJECT_DIRECTORY)s
events = TICK_60
stdout_logfile = %(ENV_AA_PROJECT_DIRECTORY)s/log/memmon.log
stderr_logfile = %(ENV_AA_PROJECT_DIRECTORY)s/log/memmon.log

[group:myauth]
programs=beat,worker,worker_services
priority = 999
