[pytest]
DJANGO_SETTINGS_MODULE = testauth.settings.local
pythonpath = .
python_files = tests.py test_*.py *_tests.py
testpaths = industry_reforged/tests
addopts = -v
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
