[tox]
requires =
    tox>=4.2
env_list =
    py{313, 312, 311, 310}

[testenv]
deps =
    allianceauth
    django-webtest
    factory_boy
    pytest
    pytest-cov
    pytest-django
set_env =
    DJANGO_SETTINGS_MODULE = testauth.settings.local
commands =
    pytest --cov=industry_reforged --cov-report=xml --cov-report=html
install_command = python -m pip install -U {opts} {packages}
