# Generated by Django 5.2.15 on 2026-06-19 15:05

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0007_productiontask_bom_parent_productiontask_hidden_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corphangarconfig",
            name="flag_id",
            field=models.CharField(
                help_text="The hangar flag ID (e.g. CorpSAG1)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="corpinventory",
            name="flag_id",
            field=models.CharField(max_length=50),
        ),
    ]
