# Generated by Django 5.2.15 on 2026-06-15 17:16

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        ("industry_reforged", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app"),
                    ("corp_access", "Can access corporate industry jobs"),
                ),
            },
        ),
        migrations.CreateModel(
            name="CharacterIndustryJob",
            fields=[
                ("job_id", models.IntegerField(primary_key=True, serialize=False)),
                ("activity_id", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("runs", models.IntegerField(default=1)),
                ("probability", models.FloatField(blank=True, null=True)),
                ("successful_runs", models.IntegerField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                ("facility_id", models.BigIntegerField(blank=True, null=True)),
                ("station_id", models.BigIntegerField(blank=True, null=True)),
                ("location_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "blueprint_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_jobs",
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Industry Job",
                "verbose_name_plural": "Character Industry Jobs",
            },
        ),
        migrations.CreateModel(
            name="CorporationIndustryJob",
            fields=[
                ("job_id", models.IntegerField(primary_key=True, serialize=False)),
                ("activity_id", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("runs", models.IntegerField(default=1)),
                ("probability", models.FloatField(blank=True, null=True)),
                ("successful_runs", models.IntegerField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                ("facility_id", models.BigIntegerField(blank=True, null=True)),
                ("station_id", models.BigIntegerField(blank=True, null=True)),
                ("location_id", models.BigIntegerField(blank=True, null=True)),
                ("wallet_division", models.IntegerField(blank=True, null=True)),
                (
                    "blueprint_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_jobs",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
                (
                    "installer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installed_corp_jobs",
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corporation Industry Job",
                "verbose_name_plural": "Corporation Industry Jobs",
            },
        ),
        migrations.CreateModel(
            name="CorporationSyncConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "corporation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_sync_config",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
                (
                    "sync_character",
                    models.ForeignKey(
                        help_text="Character with Director roles used for syncing.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corporation Sync Configuration",
                "verbose_name_plural": "Corporation Sync Configurations",
            },
        ),
    ]
