# Generated by Django 5.2.15 on 2026-06-16 20:48

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0003_characterplanet_planetpin"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetpin",
            name="install_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
