# Generated by Django 5.2.15 on 2026-06-21 20:54

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0009_corpwalletdivision_corpwalletjournal"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetpin",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
