# Generated by Django 5.2.15 on 2026-06-26 16:50

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0011_corpitemconfig_last_low_stock_warning_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberorder",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memberorder",
            name="quoted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
