# Generated by Django 5.2.15 on 2026-06-29 19:24

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0012_memberorder_accepted_at_memberorder_quoted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="corppricingconfig",
            name="builder_reward_percent",
            field=models.FloatField(
                default=0.0,
                help_text="Percentage of the item value given as a financial reward to the builder",
            ),
        ),
        migrations.AddField(
            model_name="productiontask",
            name="builder_reward",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Actual calculated ISK payout reward for completing this task",
                max_digits=17,
            ),
        ),
    ]
