# Generated by Django 5.2.15 on 2026-07-01 11:42

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0013_corppricingconfig_builder_reward_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corphangarconfig",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Include this hangar in inventory syncs"
            ),
        ),
    ]
