# Generated by Django 5.2.15 on 2026-07-01 13:23

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "industry_reforged",
            "0015_memberorder_is_paid_memberorder_payment_reference_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="corporationwebhookconfig",
            name="directors_webhook",
            field=models.URLField(
                blank=True,
                help_text="Webhook URL for Director-specific action alerts (e.g. New Quotes Requested, Orders Ready for Delivery).",
                null=True,
            ),
        ),
    ]
