# Generated by Django 5.2.15 on 2026-07-01 14:30

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0016_corporationwebhookconfig_directors_webhook"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskExecutionLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("RUNNING", "Running"),
                        ],
                        default="RUNNING",
                        max_length=20,
                    ),
                ),
                ("last_run", models.DateTimeField(auto_now=True)),
                ("duration_seconds", models.FloatField(default=0.0)),
                ("message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Task Execution Log",
                "verbose_name_plural": "Task Execution Logs",
            },
        ),
    ]
