# Generated by Django 5.2.15 on 2026-07-01 20:29

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0017_taskexecutionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberorder",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
        migrations.AddField(
            model_name="memberorder",
            name="upfront_payment",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=17),
        ),
    ]
