# Generated by Django 5.2.15 on 2026-07-05 19:39

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "industry_reforged",
            "0018_memberorder_amount_paid_memberorder_upfront_payment",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryFacility",
            fields=[
                (
                    "facility_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("owner_id", models.IntegerField(blank=True, null=True)),
                ("solar_system_id", models.IntegerField(blank=True, null=True)),
                ("type_id", models.IntegerField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Industry Facility",
                "verbose_name_plural": "Industry Facilities",
            },
        ),
    ]
