# Generated by Django 5.2.15 on 2026-07-08 17:50

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0019_industryfacility"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryRig",
            fields=[
                (
                    "type_id",
                    models.IntegerField(
                        help_text="EveType ID of the Rig",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "me_bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Bonus as percentage (e.g. 2.0 for 2%)",
                        max_digits=5,
                    ),
                ),
                (
                    "te_bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Bonus as percentage (e.g. 20.0 for 20%)",
                        max_digits=5,
                    ),
                ),
                (
                    "applies_to_groups",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of EveGroup IDs this rig applies to. E.g. '419' for Battlecruisers",
                        null=True,
                    ),
                ),
                (
                    "applies_to_categories",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of EveCategory IDs this rig applies to. E.g. '6' for Ships",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="industryfacility",
            name="security_space",
            field=models.CharField(
                choices=[
                    ("HIGHSEC", "High Security (1.0 - 0.5)"),
                    ("LOWSEC", "Low Security (0.4 - 0.1)"),
                    ("NULLSEC_WH", "Null Security / Wormhole (0.0 - -1.0)"),
                ],
                default="HIGHSEC",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="memberorder",
            name="target_facility",
            field=models.ForeignKey(
                blank=True,
                help_text="The facility where this order is planned to be built, used for quote calculation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_orders",
                to="industry_reforged.industryfacility",
            ),
        ),
        migrations.CreateModel(
            name="IndustryFacilityRig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rigs",
                        to="industry_reforged.industryfacility",
                    ),
                ),
                (
                    "rig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="industry_reforged.industryrig",
                    ),
                ),
            ],
            options={
                "unique_together": {("facility", "rig")},
            },
        ),
    ]
