# Generated by Django 5.2.15 on 2026-07-08 19:15

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "industry_reforged",
            "0020_industryrig_industryfacility_security_space_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productiontask",
            name="activity_id",
            field=models.IntegerField(default=1),
        ),
    ]
