# Generated by Django 5.2.15 on 2026-07-08 21:42

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0021_productiontask_activity_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="planetpin",
            name="capacity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="planetpin",
            name="contents",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="planetpin",
            name="contents_volume",
            field=models.FloatField(default=0.0),
        ),
    ]
