# Generated by Django 5.2.15 on 2026-07-09 11:49

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0022_planetpin_capacity_planetpin_contents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpitemconfig",
            name="blacklist_from_orders",
            field=models.BooleanField(
                default=False,
                help_text="Remove this item from member orders automatically.",
            ),
        ),
        migrations.AddField(
            model_name="corpitemconfig",
            name="blacklist_warning_message",
            field=models.CharField(
                blank=True,
                help_text="Message to display to the user if this item is removed (e.g. 'Please acquire deadspace items yourself').",
                max_length=255,
                null=True,
            ),
        ),
    ]
