# Generated by Django 5.2.15 on 2026-07-09 12:05

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0023_corpitemconfig_blacklist_from_orders_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="corpitemconfig",
            old_name="blacklist_from_orders",
            new_name="exclude_from_orders",
        ),
        migrations.RenameField(
            model_name="corpitemconfig",
            old_name="blacklist_warning_message",
            new_name="exclude_warning_message",
        ),
    ]
