# Generated by Django 5.2.15 on 2026-07-09 13:48

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        (
            "industry_reforged",
            "0024_rename_blacklist_from_orders_corpitemconfig_exclude_from_orders_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="corpinventory",
            unique_together={("corporation", "item_type", "location_id")},
        ),
        migrations.DeleteModel(
            name="CorpHangarConfig",
        ),
        migrations.RemoveField(
            model_name="corpinventory",
            name="flag_id",
        ),
    ]
