# Generated by Django 5.2.15 on 2026-07-09 16:14

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0025_alter_corpinventory_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryfacility",
            name="sync_inventory",
            field=models.BooleanField(
                default=False, help_text="Sync corporate inventory from this facility."
            ),
        ),
    ]
