# Generated by Django 5.2.15 on 2026-07-09 19:51

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0026_industryfacility_sync_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryfacility",
            name="is_production_facility",
            field=models.BooleanField(
                default=False,
                help_text="Whether this facility is configured as a production facility.",
            ),
        ),
    ]
