# Generated by Django 5.2.15 on 2026-07-12 11:18

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0027_industryfacility_is_production_facility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corpitemconfig",
            name="bom_source",
        ),
    ]
