# Generated by Django 5.2.15 on 2026-07-12 12:49

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        ("industry_reforged", "0028_remove_corpitemconfig_bom_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpitemconfig",
            name="bom_source",
            field=models.CharField(
                choices=[("SDE", "Eve SDE (Database)"), ("FUZZWORK", "Fuzzwork API")],
                default="FUZZWORK",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="corppricingconfig",
            name="default_t1_me",
            field=models.IntegerField(
                default=10,
                help_text="Default Material Efficiency (ME) for Tech I blueprints",
            ),
        ),
        migrations.AddField(
            model_name="corppricingconfig",
            name="default_t2_me",
            field=models.IntegerField(
                default=2,
                help_text="Default Material Efficiency (ME) for Tech II blueprints",
            ),
        ),
        migrations.CreateModel(
            name="OrderBlueprintOverride",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manual_me", models.IntegerField(default=0)),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bp_overrides",
                        to="industry_reforged.memberorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order BP Override",
                "verbose_name_plural": "Order BP Overrides",
                "unique_together": {("order", "item_type")},
            },
        ),
    ]
