# Generated by Django 5.2.15 on 2026-07-13 08:53

# Django
from django.db import migrations


def seed_rigs(apps, schema_editor):
    IndustryRig = apps.get_model("industry_reforged", "IndustryRig")
    rigs = [
        {
            "type_id": 37473,
            "name": "Standup M-Set Equipment Manufacturing Material Efficiency I",
            "me_bonus": 2.0,
            "te_bonus": 20.0,
            "applies_to_categories": "65",
        },
        {
            "type_id": 37474,
            "name": "Standup M-Set Equipment Manufacturing Material Efficiency II",
            "me_bonus": 2.4,
            "te_bonus": 24.0,
            "applies_to_categories": "65",
        },
        {
            "type_id": 37172,
            "name": "Standup L-Set Ship Manufacturing Material Efficiency I",
            "me_bonus": 2.0,
            "te_bonus": 20.0,
            "applies_to_categories": "6",
        },
        {
            "type_id": 37173,
            "name": "Standup L-Set Ship Manufacturing Material Efficiency II",
            "me_bonus": 2.4,
            "te_bonus": 24.0,
            "applies_to_categories": "6",
        },
        {
            "type_id": 37180,
            "name": "Standup L-Set Equipment Manufacturing Material Efficiency I",
            "me_bonus": 2.0,
            "te_bonus": 20.0,
            "applies_to_categories": "65",
        },
        {
            "type_id": 37181,
            "name": "Standup L-Set Equipment Manufacturing Material Efficiency II",
            "me_bonus": 2.4,
            "te_bonus": 24.0,
            "applies_to_categories": "65",
        },
        {
            "type_id": 37260,
            "name": "Standup XL-Set Ship Manufacturing Material Efficiency I",
            "me_bonus": 2.0,
            "te_bonus": 20.0,
            "applies_to_categories": "6",
        },
        {
            "type_id": 37261,
            "name": "Standup XL-Set Ship Manufacturing Material Efficiency II",
            "me_bonus": 2.4,
            "te_bonus": 24.0,
            "applies_to_categories": "6",
        },
    ]
    for rig_data in rigs:
        IndustryRig.objects.update_or_create(
            type_id=rig_data["type_id"],
            defaults={
                "name": rig_data["name"],
                "me_bonus": rig_data["me_bonus"],
                "te_bonus": rig_data["te_bonus"],
                "applies_to_categories": rig_data["applies_to_categories"],
                "applies_to_groups": "",
            },
        )


def reverse_seed_rigs(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0029_corpitemconfig_bom_source_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_rigs, reverse_seed_rigs),
    ]
