# Generated by Django 5.2.15 on 2026-07-13 12:37

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0030_auto_20260713_0853"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberorder",
            name="parent_order",
            field=models.ForeignKey(
                blank=True,
                help_text="If this order was split, this is the parent order.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_orders",
                to="industry_reforged.memberorder",
            ),
        ),
    ]
