# Generated by Django 5.2.15 on 2026-07-15 10:34

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0031_memberorder_parent_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="industryfacility",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the default facility for the corporation.",
            ),
        ),
    ]
