# Generated by Django 5.2.15 on 2026-07-15 19:18

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0032_industryfacility_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpitemconfig",
            name="max_runs",
            field=models.IntegerField(
                default=0, help_text="Max runs per BPC (0 = infinite/BPO)"
            ),
        ),
        migrations.AddField(
            model_name="orderblueprintoverride",
            name="max_runs",
            field=models.IntegerField(default=0),
        ),
    ]
