# Generated by Django 5.2.15 on 2026-07-16 14:44

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0033_corpitemconfig_max_runs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberorder",
            name="parent_order",
            field=models.ForeignKey(
                blank=True,
                help_text="If this order was split, this is the parent order.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_orders",
                to="industry_reforged.memberorder",
            ),
        ),
    ]
