# Generated by Django 5.2.15 on 2026-07-18 13:16

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0034_alter_memberorder_parent_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpwalletdivision",
            name="warning_threshold",
            field=models.BigIntegerField(
                default=500000000,
                help_text="Balance below which a warning is sent (default: 500 million ISK).",
            ),
        ),
    ]
