# Generated by Django 5.2.15 on 2026-07-19 17:15

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        ("industry_reforged", "0035_corpwalletdivision_warning_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorpBuyOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("FULFILLED", "Fulfilled"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_orders",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corporate Buy Order",
                "verbose_name_plural": "Corporate Buy Orders",
            },
        ),
    ]
