# Generated by Django 4.2.14 on 2026-07-28 18:28

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0001_initial"),
        ("industry_reforged", "0036_corpbuyorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterplanet",
            name="eve_planet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="eveuniverse.eveplanet",
            ),
        ),
        migrations.AddField(
            model_name="characterplanet",
            name="eve_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="eveuniverse.evesolarsystem",
            ),
        ),
    ]
