# Generated by Django 5.2.16 on 2026-08-06 10:06

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0038_userpiconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corppricingconfig",
            name="default_discount_percent",
            field=models.FloatField(
                default=0.0,
                help_text="Default discount percentage applied to Jita prices (e.g. 10.0 for 10 percent off)",
            ),
        ),
        migrations.AlterField(
            model_name="corptypediscount",
            name="discount_percent",
            field=models.FloatField(
                help_text="Discount percentage for this specific item type"
            ),
        ),
        migrations.AlterField(
            model_name="taxconfig",
            name="broker_fee_rate",
            field=models.FloatField(default=0.0, help_text="Broker fee percentage"),
        ),
        migrations.AlterField(
            model_name="taxconfig",
            name="industry_tax_rate",
            field=models.FloatField(
                default=0.0, help_text="Tax percentage applied to industry jobs"
            ),
        ),
        migrations.CreateModel(
            name="TaskJobLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linked_runs", models.IntegerField(default=1)),
                (
                    "character_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="industry_reforged.characterindustryjob",
                    ),
                ),
                (
                    "corporation_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="industry_reforged.corporationindustryjob",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_jobs",
                        to="industry_reforged.productiontask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Job Link",
                "verbose_name_plural": "Task Job Links",
            },
        ),
    ]
