# Generated by Django 5.2.15 on 2026-08-07 07:46

# Standard Library
import logging

# Django
from django.db import migrations

logger = logging.getLogger(__name__)


def cleanup_orphaned_tasks(apps, schema_editor):
    ProductionTask = apps.get_model("industry_reforged", "ProductionTask")

    # We found that deleting a main order correctly deleted its child orders via CASCADE,
    # but the tasks associated with those child orders were orphaned (created_from_order set to NULL)
    # due to on_delete=SET_NULL. This migration cleans them up.

    # Clean up all tasks that do not have a linked order (and which are not manual spawns, if any exist).
    # Since manual spawns also have created_from_order=None, we might delete them too,
    # but based on the user's issue, orphaned tasks are the primary concern here.
    orphans = ProductionTask.objects.filter(created_from_order__isnull=True)
    count = orphans.count()
    if count > 0:
        logger.info(f"Deleting {count} orphaned ProductionTasks.")
        orphans.delete()


def reverse_cleanup(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "industry_reforged",
            "0039_alter_corppricingconfig_default_discount_percent_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(cleanup_orphaned_tasks, reverse_cleanup),
    ]
