# Generated by Django 5.2.15 on 2026-08-07 11:10

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        ("industry_reforged", "0040_cleanup_orphaned_tasks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "Income (Member Payment)"),
                            ("PAYOUT", "Payout (Builder Batch)"),
                            ("PROCUREMENT", "Procurement (Buy Order)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("reference", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_transactions",
                        to="eveonline.evecharacter",
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="industry_reforged.memberorder",
                    ),
                ),
                (
                    "payout_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="industry_reforged.builderpayoutbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger Transaction",
                "verbose_name_plural": "Ledger Transactions",
                "ordering": ["-date"],
            },
        ),
    ]
