# Generated by Django 5.2.15 on 2026-08-07 11:10

# Django
from django.db import migrations


def migrate_existing_transactions(apps, schema_editor):
    MemberOrder = apps.get_model("industry_reforged", "MemberOrder")
    BuilderPayoutBatch = apps.get_model("industry_reforged", "BuilderPayoutBatch")
    LedgerTransaction = apps.get_model("industry_reforged", "LedgerTransaction")

    # Member Orders
    for order in MemberOrder.objects.filter(is_paid=True):
        if order.amount_paid > 0:
            tx = LedgerTransaction.objects.create(
                transaction_type="INCOME",
                amount=order.amount_paid,
                character=order.character,
                director=None,  # We don't know who marked it paid historically
                reference=f"Order #{order.id}",
                notes="Migrated from old paid order",
                member_order=order,
            )
            # update date since auto_now_add=True overrides it on create
            tx.date = order.updated_at
            tx.save(update_fields=["date"])

    # Builder Payout Batches
    for batch in BuilderPayoutBatch.objects.filter(status="PAID"):
        if batch.total_amount > 0:
            tx = LedgerTransaction.objects.create(
                transaction_type="PAYOUT",
                amount=batch.total_amount,
                character=batch.builder,
                director=None,
                reference=batch.payment_reference,
                notes="Migrated from old paid batch",
                payout_batch=batch,
            )
            # update date since auto_now_add=True overrides it on create
            if batch.paid_at:
                tx.date = batch.paid_at
            else:
                tx.date = batch.created_at
            tx.save(update_fields=["date"])


def reverse_migration(apps, schema_editor):
    LedgerTransaction = apps.get_model("industry_reforged", "LedgerTransaction")
    LedgerTransaction.objects.filter(notes__startswith="Migrated").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0041_add_ledger_transaction"),
    ]

    operations = [
        migrations.RunPython(migrate_existing_transactions, reverse_migration)
    ]
