# Generated by Django 5.2.16 on 2026-08-27 09:55

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        ("industry_reforged", "0043_restore_active_titans_and_long_jobs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="corporationwebhookconfig",
            name="blueprint_requests_webhook",
            field=models.URLField(
                blank=True,
                help_text="Webhook URL for new Blueprint Requests.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BlueprintRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("PROCESSED", "Processed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "requested_quantity",
                    models.IntegerField(
                        default=1, help_text="Number of copies requested"
                    ),
                ),
                (
                    "requested_runs",
                    models.IntegerField(default=1, help_text="Runs per copy requested"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_blueprint_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprint_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blueprint Request",
                "verbose_name_plural": "Blueprint Requests",
            },
        ),
        migrations.AddField(
            model_name="productiontask",
            name="created_from_blueprint_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_tasks",
                to="industry_reforged.blueprintrequest",
            ),
        ),
        migrations.CreateModel(
            name="CorpBlueprint",
            fields=[
                ("item_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("location_id", models.BigIntegerField()),
                ("location_flag", models.CharField(max_length=50)),
                ("quantity", models.IntegerField(default=-1)),
                ("time_efficiency", models.IntegerField(default=0)),
                ("material_efficiency", models.IntegerField(default=0)),
                ("runs", models.IntegerField(default=-1)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprints",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corp Blueprint",
                "verbose_name_plural": "Corp Blueprints",
            },
        ),
        migrations.AddField(
            model_name="blueprintrequest",
            name="blueprint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="industry_reforged.corpblueprint",
            ),
        ),
    ]
