# Generated by Django 5.2.16 on 2026-09-01 12:06

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        (
            "industry_reforged",
            "0044_corporationwebhookconfig_blueprint_requests_webhook_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PISchematic",
            fields=[
                (
                    "schematic_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("cycle_time", models.IntegerField(help_text="Cycle time in seconds")),
            ],
            options={
                "verbose_name": "PI Schematic",
                "verbose_name_plural": "PI Schematics",
            },
        ),
        migrations.CreateModel(
            name="PISchematicInput",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "schematic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="industry_reforged.pischematic",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PISchematicOutput",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "schematic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="industry_reforged.pischematic",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
        ),
    ]
