# Generated by Django 5.2.16 on 2026-09-01 17:18

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0045_pischematic_pischematicinput_pischematicoutput"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpiconfig",
            name="extraction_deficit_threshold_percent",
            field=models.IntegerField(
                default=100,
                help_text="Warn if extraction is below this percentage of consumption",
            ),
        ),
    ]
