# Generated by Django 5.2.15 on 2026-09-04 15:40

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        ("industry_reforged", "0046_userpiconfig_extraction_deficit_threshold_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporationPricingConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_valuation_method",
                    models.CharField(
                        choices=[
                            ("JITA_SELL", "Jita Sell (Default)"),
                            ("JITA_BUY", "Jita Buy"),
                            ("CORP_MANUAL", "Corp Manual Price (Strict)"),
                        ],
                        default="JITA_SELL",
                        help_text="The method used to value raw materials in the BOM cost calculation.",
                        max_length=20,
                    ),
                ),
                (
                    "minimum_margin_floor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The minimum profit margin percentage allowed for an order (e.g., 0.00 for 0%, -5.00 for -5% max loss).",
                        max_digits=5,
                    ),
                ),
                (
                    "corporation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_pricing_config",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corporation Pricing Configuration",
                "verbose_name_plural": "Corporation Pricing Configurations",
            },
        ),
    ]
