# Generated by Django 5.2.15 on 2026-09-04 15:47

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0047_corporationpricingconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberorder",
            name="true_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The calculated True Material Cost at the time of order creation.",
                max_digits=17,
            ),
        ),
    ]
