# Generated by Django 5.2.16 on 2026-09-05 12:08

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        ("industry_reforged", "0048_memberorder_true_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the basket", max_length=255),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this basket is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Basket",
                "verbose_name_plural": "Baskets",
            },
        ),
        migrations.CreateModel(
            name="BasketItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_stock_level",
                    models.PositiveIntegerField(
                        help_text="The minimum quantity the market should always have available."
                    ),
                ),
                (
                    "restock_threshold",
                    models.PositiveIntegerField(
                        help_text="The stock level that triggers an automatic reorder."
                    ),
                ),
                (
                    "target_market",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ESI Location ID for the target market (station or citadel).",
                        null=True,
                    ),
                ),
                (
                    "target_region",
                    models.BigIntegerField(
                        blank=True,
                        help_text="ESI Region ID for region-based market checking.",
                        null=True,
                    ),
                ),
                (
                    "min_profit_margin",
                    models.FloatField(
                        default=15.0,
                        help_text="Minimum acceptable profit margin % for building this item.",
                    ),
                ),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="industry_reforged.basket",
                    ),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basket Item",
                "verbose_name_plural": "Basket Items",
            },
        ),
        migrations.CreateModel(
            name="AIMarketLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        help_text="e.g., 'Ordered', 'Skipped'", max_length=255
                    ),
                ),
                (
                    "margin",
                    models.FloatField(
                        blank=True,
                        help_text="Calculated profit margin at the time of check",
                        null=True,
                    ),
                ),
                (
                    "stock_level",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Calculated current stock at the time of check",
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Reasoning for the action taken"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "basket_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="industry_reforged.basketitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Market Log",
                "verbose_name_plural": "AI Market Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
