# Generated by Django 5.2.15 on 2026-09-05 12:39

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        ("industry_reforged", "0049_basket_basketitem_aimarketlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketitem",
            name="min_profit_margin",
        ),
        migrations.RemoveField(
            model_name="basketitem",
            name="restock_threshold",
        ),
        migrations.RemoveField(
            model_name="basketitem",
            name="target_market",
        ),
        migrations.RemoveField(
            model_name="basketitem",
            name="target_region",
        ),
        migrations.AddField(
            model_name="basket",
            name="corporation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baskets",
                to="eveonline.evecorporationinfo",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="min_profit_margin",
            field=models.FloatField(
                default=15.0,
                help_text="Minimum acceptable profit margin % for building this basket.",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="target_region_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="ESI Region ID for region-based market checking.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="batch_size",
            field=models.PositiveIntegerField(
                default=1,
                help_text="The default batch size to order when stock is low.",
            ),
        ),
    ]
