# Generated by Django 5.2.15 on 2026-09-05 13:42

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0050_remove_basketitem_min_profit_margin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="target_hub",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific facility (hub) to monitor.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="industry_reforged.industryfacility",
            ),
        ),
    ]
