# Generated by Django 5.2.15 on 2026-09-06 10:56

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        ("industry_reforged", "0051_basket_target_hub"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnownLocation",
            fields=[
                (
                    "location_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "corporations",
                    models.ManyToManyField(
                        related_name="known_locations",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Known Location",
                "verbose_name_plural": "Known Locations",
            },
        ),
    ]
