# Generated by Django 5.2.15 on 2026-09-06 12:54

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        ("industry_reforged", "0052_knownlocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketOpportunity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_id", models.BigIntegerField(help_text="ESI Region ID")),
                ("velocity", models.FloatField(help_text="Average Daily Volume (ADV)")),
                ("margin", models.FloatField(help_text="Estimated profit margin %")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_opportunities",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Opportunity",
                "verbose_name_plural": "Market Opportunities",
                "unique_together": {("corporation", "eve_type", "region_id")},
            },
        ),
    ]
