# Generated by Django 5.2.15 on 2026-09-06 15:42

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        ("industry_reforged", "0053_marketopportunity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="marketopportunity",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="marketopportunity",
            name="target_hub",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific facility if scanned for a hub.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="industry_reforged.industryfacility",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketopportunity",
            unique_together={("corporation", "eve_type", "region_id", "target_hub")},
        ),
    ]
