# Generated by Django 5.2.15 on 2026-09-06 16:51

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0025_remove_evecharacter_last_updated_and_more"),
        ("industry_reforged", "0054_alter_marketopportunity_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityScanner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the scanner", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "target_region_id",
                    models.BigIntegerField(
                        blank=True, help_text="ESI Region ID", null=True
                    ),
                ),
                ("min_profit_margin", models.FloatField(default=15.0)),
                ("min_velocity", models.FloatField(default=1.0)),
                (
                    "categories",
                    models.JSONField(
                        default=list, help_text="List of category IDs to scan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_scanners",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
                (
                    "target_hub",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific facility if scanning a hub",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="industry_reforged.industryfacility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Scanner",
                "verbose_name_plural": "Opportunity Scanners",
            },
        ),
    ]
