# Generated by Django 5.2.15 on 2026-09-06 17:13

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0055_opportunityscanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityscanner",
            name="auto_add_basket",
            field=models.ForeignKey(
                blank=True,
                help_text="Automatically add profitable items to this basket.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="industry_reforged.basket",
            ),
        ),
        migrations.AddField(
            model_name="opportunityscanner",
            name="target_stock_days",
            field=models.IntegerField(
                default=7,
                help_text="If auto-adding, how many days of stock to maintain based on daily velocity.",
            ),
        ),
    ]
