# Generated by Django 5.2.15 on 2026-09-06 17:24

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0056_opportunityscanner_auto_add_basket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityscanner",
            name="last_run",
            field=models.DateTimeField(
                blank=True,
                help_text="The last time this scanner was executed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opportunityscanner",
            name="run_interval_hours",
            field=models.IntegerField(
                default=24,
                help_text="How often (in hours) should this scanner run automatically.",
            ),
        ),
        migrations.CreateModel(
            name="OpportunityScannerLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items_scanned", models.PositiveIntegerField(default=0)),
                ("opportunities_found", models.PositiveIntegerField(default=0)),
                ("items_auto_added", models.PositiveIntegerField(default=0)),
                ("details", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "scanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="industry_reforged.opportunityscanner",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
