# Generated by Django 5.2.15 on 2026-09-06 17:42

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0012_alter_evebloodline_eve_ship_type"),
        ("industry_reforged", "0057_opportunityscanner_last_run_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityscanner",
            name="scan_missing_blueprints",
            field=models.BooleanField(
                default=False,
                help_text="Also scan for profitable items that the corporation does NOT own blueprints for.",
            ),
        ),
        migrations.CreateModel(
            name="MissingBlueprintOpportunity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("velocity", models.FloatField()),
                ("margin", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "eve_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evetype",
                    ),
                ),
                (
                    "scanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missing_opportunities",
                        to="industry_reforged.opportunityscanner",
                    ),
                ),
            ],
            options={
                "ordering": ["-margin"],
            },
        ),
    ]
