# Generated by Django 5.2.15 on 2026-09-06 18:06

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "industry_reforged",
            "0058_opportunityscanner_scan_missing_blueprints_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityscanner",
            name="is_running",
            field=models.BooleanField(
                default=False,
                help_text="Whether the scanner is currently running in the background.",
            ),
        ),
    ]
