# Generated by Django 5.2.15 on 2026-09-06 18:21

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0059_opportunityscanner_is_running"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="is_running",
            field=models.BooleanField(
                default=False,
                help_text="Whether the basket is currently being evaluated in the background.",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="last_run",
            field=models.DateTimeField(
                blank=True,
                help_text="The last time this basket was evaluated.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="run_interval_hours",
            field=models.IntegerField(
                default=24,
                help_text="How often (in hours) should this basket run automatically.",
            ),
        ),
    ]
