# Generated by Django 5.2.15 on 2026-09-07 17:02

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0060_basket_is_running_basket_last_run_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporationwebhookconfig",
            name="ai_jobs_webhook",
            field=models.URLField(
                blank=True,
                help_text="Webhook URL for new AI-generated Production Tasks.",
                null=True,
            ),
        ),
    ]
