# Generated by Django 5.2.17 on 2026-09-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_reforged', '0062_opportunityscannerlog_evaluation_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketopportunity',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, help_text='AI Confidence Score (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='marketopportunity',
            name='forecasted_velocity',
            field=models.FloatField(blank=True, help_text='AI Forecasted Daily Volume', null=True),
        ),
    ]
