# Generated by Django 5.2.17 on 2026-09-14 15:20

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry_reforged", "0063_marketopportunity_ai_confidence_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productiontask",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("MEMBER_ORDER", "Member Order"),
                    ("BASKET", "Market Basket / AI"),
                    ("BOM", "BOM Component"),
                    ("BLUEPRINT", "Blueprint Request"),
                ],
                default="MANUAL",
                max_length=20,
            ),
        ),
    ]
