# Generated by Django 5.2.17 on 2026-09-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_reforged', '0064_productiontask_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryfacility',
            name='is_default_reaction',
            field=models.BooleanField(default=False, help_text='Whether this is the default facility for reactions.'),
        ),
    ]
