# Generated by Django 5.2.17 on 2026-10-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_reforged', '0066_memberorder_ignore_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorder',
            name='upfront_payment_plex',
            field=models.IntegerField(default=0, help_text='Upfront payment required in PLEX'),
        ),
    ]
