# Generated by Django 5.2.17 on 2026-10-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry_reforged', '0067_memberorder_upfront_payment_plex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpitemconfig',
            name='bom_source',
        ),
    ]
