# Generated by Django 5.2.17 on 2026-10-09 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
        ('industry_reforged', '0070_corpitemconfig_is_unclaimable_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_bought',
            field=models.BooleanField(
                default=False,
                help_text='Indicates if this product has been purchased for the order',
            ),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bought_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Timestamp when this item was marked as bought',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bought_by',
            field=models.ForeignKey(
                blank=True,
                help_text='The character who purchased this item',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='eveonline.evecharacter',
            ),
        ),
    ]
